### ISSUE TITLE
File not found exception

### ISSUE THREAD

**Issue by hswick** [ds923y/nd4clj#3]
Requiring nd4clj into my project results in this error:    
Error compiling: nd4clj/matrix.clj:1:1 Could not locate                      
   clojure/core/matrix/compliance_tester__init.class or                         
   clojure/core/matrix/compliance_tester.clj on classpath. Please               
   check that namespaces with dashes use underscores in the Clojure             
   file name.  

core.matrix is installed on my machine, and it is version 0.56.0

**Comment by hswick** [comment]
Realized that this is probably on my end

**Comment by jimmyhmiller** [comment]
@hswick Did you find a fix for this?

**Comment by hswick** [comment]
@jimmyhmiller yeah I wrote another library https://github.com/hswick/jutsu.matrix
